[tool.poetry]
name = "job-search"
version = "0.1.0"
description = ""
authors = ["HAN <han82@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
